# Theme Settings
theme: null   # REQUIRED because you're using a remote theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # REQUIRED to specify the theme and version
minimal_mistakes_skin    : "miniwolke" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
title             : "MiniWokleDesign"
name              : "MiniWokleDesign"
url               : "http://MiniWokleDesign.github.io"
repository        : "MiniWokleDesign/MiniWokleDesign.github.io"
logo                     : "/assets/images/logo/MiniWokleDesign-logo.png"

# Site Author
author:
  name             : "Yun"
  avatar           : "/assets/images/logo/yun.jpg"
  bio              : "Hi, my name is Yun from Taiwan. I have been working as a graphics designer in Taiwan, Japan, and now in Austria. I have experienced multiple cultures that inspire the design in MiniWolkeDesign. Accessories here are all about my life."
  location        : "Austria"
  email           :
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://MiniWokleDesign.github.io"
    - label: "Contact"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:miniwolkedesign@gmail.com"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/MiniWolkeDesign"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/miniwolkedesign"
    - label: "Shop on Etsy"
      icon: "fas fa-fw fa-link"
      url: "https://www.etsy.com/shop/MiniWolkeDesign"
    - label: "Shop on OpenSea"
      icon: "fas fa-fw fa-link"
      url: "https://opensea.io/miniwolke"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "http://MiniWokleDesign.github.io"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/MiniWolkeDesign"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/miniwolkedesign"
      

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache # REQUIRED to use include_cached
  - jekyll-feed
  - jekyll-seo-tag


